"""Add round status

Revision ID: 0b8d37f2240f
Revises: a6ac6b7878d4
Create Date: 2026-06-08 14:08:59.664650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8d37f2240f'
down_revision = 'a6ac6b7878d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=16), nullable=False, server_default='DRAFT')
        )
        batch_op.create_index(batch_op.f('ix_rounds_status'), ['status'], unique=False)

    # ### end Alembic commands ###
    # Drop the server default once existing rows are backfilled - new rows should always
    # set status explicitly (see Round model / admin blueprint), not rely on a DB default.
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
