"""Initial schema

Revision ID: 3c49f6391187
Revises: 
Create Date: 2026-06-08 13:30:43.808272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c49f6391187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(), nullable=False),
    sa.Column('is_knockout', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('home_score_90', sa.Integer(), nullable=True),
    sa.Column('away_score_90', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fixtures_kickoff_at'), ['kickoff_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_round_id'), ['round_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('predicted_home', sa.Integer(), nullable=False),
    sa.Column('predicted_away', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fixture_id', name='uq_prediction_user_fixture')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_fixture_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_round_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_kickoff_at'))
        batch_op.drop_index(batch_op.f('ix_fixtures_external_id'))

    op.drop_table('fixtures')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('rounds')
    # ### end Alembic commands ###
