"""Add poll_logs table

Revision ID: 654295109d29
Revises: 3c49f6391187
Create Date: 2026-06-08 13:52:00.093965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654295109d29'
down_revision = '3c49f6391187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('fixtures_created', sa.Integer(), nullable=False),
    sa.Column('fixtures_updated', sa.Integer(), nullable=False),
    sa.Column('fixtures_scored', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_logs_run_at'), ['run_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_logs_run_at'))

    op.drop_table('poll_logs')
    # ### end Alembic commands ###
