"""Add push notification flags to gameweeks

Revision ID: 8e14a4560d1d
Revises: 981a747acc51
Create Date: 2026-08-31 19:19:48.839453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e14a4560d1d'
down_revision = '981a747acc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_24h', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('notified_1h', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.alter_column('notified_24h', server_default=None)
        batch_op.alter_column('notified_1h', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.drop_column('notified_1h')
        batch_op.drop_column('notified_24h')

    # ### end Alembic commands ###
