"""add round entries table

Revision ID: 9747c48e2a40
Revises: 0b8d37f2240f
Create Date: 2026-06-08 18:12:15.275928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9747c48e2a40'
down_revision = '0b8d37f2240f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_round_entry_user_round')
    )
    with op.batch_alter_table('round_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_entries_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_round_entries_round_id'))

    op.drop_table('round_entries')
    # ### end Alembic commands ###
