"""add short_name columns to fixtures

Revision ID: 9defc92b1097
Revises: 760005299371
Create Date: 2026-06-09 23:15:04.504558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9defc92b1097'
down_revision = '760005299371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_short_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('away_short_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('away_short_name')
        batch_op.drop_column('home_short_name')

    # ### end Alembic commands ###
