"""Add round description

Revision ID: a6ac6b7878d4
Revises: 654295109d29
Create Date: 2026-06-08 13:57:13.094793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac6b7878d4'
down_revision = '654295109d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
