"""add current_minute and current_injury_time to fixtures

Revision ID: c7d8e9f0a1b2
Revises: d1a2b3c4e5f6
Create Date: 2026-06-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = 'd1a2b3c4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_injury_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('current_injury_time')
        batch_op.drop_column('current_minute')

    # ### end Alembic commands ###
