"""Add manually_corrected to fixtures

Revision ID: cd440f8d3dd2
Revises: c7d8e9f0a1b2
Create Date: 2026-06-30 00:45:06.729113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd440f8d3dd2'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: NOT NULL with no default fails against a populated
    # fixtures table (existing rows have no value to backfill from) - only ever
    # succeeded before against an empty table, which masked this on first release.
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manually_corrected', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('manually_corrected')

    # ### end Alembic commands ###
