"""Add notified_permutations to gameweeks

Revision ID: ef261b4fe695
Revises: 8e14a4560d1d
Create Date: 2026-09-17 23:42:39.650716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef261b4fe695'
down_revision = '8e14a4560d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (see 8e14a4560d1d for the same
    # pattern with notified_24h/notified_1h), then is dropped so future inserts
    # rely on the model's default=False instead of the DB schema.
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_permutations', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.alter_column('notified_permutations', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameweeks', schema=None) as batch_op:
        batch_op.drop_column('notified_permutations')

    # ### end Alembic commands ###
